trigger:
- main

variables:
  imageName: azure-pipelines-canary-k8s
  dockerRegistryServiceConnection: fstefanovacrlearning
  imageRepository: 'azure-pipelines-canary-k8s'
  containerRegistry: fstefanovacrlearning.azurecr.io
  tag: $[ substring( variables['Build.SourceVersion'], 0, 7 ) ]
  kubernetesCluster: 'aks-learning'
  resourceGroup: 'az204-learning'


pool:
  name: "Azure Pipelines"

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: app/Dockerfile
        tags: |
          $(tag)

    - publish: manifests
      artifact: manifests

    - publish: misc
      artifact: misc

- stage: DeployCanary
  displayName: Deploy canary
  dependsOn: Build
  condition: succeeded()
  
  jobs:
  - deployment: Deploycanary
    displayName: Deploy canary
    environment: 'akscanary'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@1
            displayName: Create Docker Registry Secret
            inputs:
              action: 'createSecret'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'fstefanov-sub-conn'
              azureResourceGroup: $(resourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              secretType: 'dockerRegistry'
              secretName: 'my-acr-secret'
              dockerRegistryEndpoint: 'fstefanovacrlearning'

          - task: KubernetesManifest@1
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'fstefanov-sub-conn'
              azureResourceGroup: $(resourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              strategy: 'canary'
              percentage: '25'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
              imagePullSecrets: 'my-acr-secret'
              rolloutStatusTimeout:  '300'
          - task: KubernetesManifest@1
            displayName: Deploy Forbio to Kubernetes cluster
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'fstefanov-sub-conn'
              azureResourceGroup: $(resourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              manifests: '$(Pipeline.Workspace)/misc/*'


- stage: PromoteRejectCanary
  displayName: Promote or Reject canary
  dependsOn: DeployCanary
  condition: succeeded()
  jobs:
  - deployment: PromoteCanary
    displayName: Promote Canary
    environment: 'akspromote'
    strategy:
      runOnce:
        deploy:
          steps:      
          - task: KubernetesManifest@1
            displayName: Create Docker Registry Secret for akspromote
            inputs:
              action: 'createSecret'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'fstefanov-sub-conn'
              azureResourceGroup: $(resourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              secretType: 'dockerRegistry'
              secretName: 'my-acr-secret'
              dockerRegistryEndpoint: 'fstefanovacrlearning'

          - task: KubernetesManifest@1
            displayName: promote canary
            inputs:
              action: 'promote'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'fstefanov-sub-conn'
              azureResourceGroup: $(resourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              strategy: 'canary'
              manifests: '$(Pipeline.Workspace)/manifests/*'
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
              imagePullSecrets: 'my-acr-secret'

- stage: RejectCanary
  displayName: Reject canary
  dependsOn: PromoteRejectCanary
  condition: failed()

  jobs:
  - deployment: RejectCanary
    displayName: Reject Canary
    pool: 
      vmImage: ubuntu-latest
    environment: 'akscanary'
    strategy:
      runOnce:
        deploy:
          steps:        
          - task: KubernetesManifest@1
            displayName: Create Docker Registry Secret for reject canary
            inputs:
              action: 'createSecret'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'fstefanov-sub-conn'
              azureResourceGroup: $(resourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              secretType: 'dockerRegistry'
              secretName: 'my-acr-secret'
              dockerRegistryEndpoint: 'fstefanovacrlearning'    
          - task: KubernetesManifest@1
            displayName: Reject canary deployment
            inputs:
              action: 'reject'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'fstefanov-sub-conn'
              azureResourceGroup: $(resourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              namespace: 'default'
              strategy: 'canary'
              manifests: '$(Pipeline.Workspace)/manifests/*'
