trigger:
- main

variables:
  imageName: azure-pipelines-canary-k8s
  dockerRegistryServiceConnection: fstefanovacrlearning
  imageRepository: 'azure-pipelines-canary-k8s'
  containerRegistry: fstefanovacrlearning.azurecr.io
  tag: $[ substring( variables['Build.SourceVersion'], 0, 7 ) ]

pool:
  name: "Azure Pipelines"

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: app/Dockerfile
        tags: |
          $(tag)

    - publish: manifests
      artifact: manifests

    - publish: misc
      artifact: misc

- stage: DeployCanary
  displayName: Deploy canary
  dependsOn: Build
  condition: succeeded()
  
  jobs:
  - deployment: Deploycanary
    displayName: Deploy canary
    environment: 'akscanary'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@1
            displayName: Create Docker Registry Secret
            inputs:
              action: 'createSecret'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'fstefanov-sub-conn'
              azureResourceGroup: 'az204-learning'
              kubernetesCluster: 'aks-learning'
              secretType: 'dockerRegistry'
              secretName: 'my-acr-secret'
              dockerRegistryEndpoint: 'fstefanovacrlearning'